#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#ifdef CONFIG_SD_CARD_MMC_INTERFACE
// Define to use 4-bit SDMMC bus width; comment out to use 1-bit bus width
// #define CARD_SDMMC_BUS_WIDTH_4BIT

#ifdef CARD_SDMMC_BUS_WIDTH_4BIT
#define CARD_SDMMC_CLK_GPIO GPIO_NUM_3  // CLK pin
#define CARD_SDMMC_CMD_GPIO GPIO_NUM_2  // CMD pin
#define CARD_SDMMC_D0_GPIO  GPIO_NUM_1  // D0 pin
#define CARD_SDMMC_D1_GPIO  GPIO_NUM_NC
#define CARD_SDMMC_D2_GPIO  GPIO_NUM_NC
#define CARD_SDMMC_D3_GPIO  GPIO_NUM_46 // D3 pin
#else
#define CARD_SDMMC_CLK_GPIO GPIO_NUM_47 // CLK pin
#define CARD_SDMMC_CMD_GPIO GPIO_NUM_48 // CMD pin
#define CARD_SDMMC_D0_GPIO  GPIO_NUM_21 // D0 pin
#define CARD_SDMMC_D3_GPIO  GPIO_NUM_NC
#endif
#endif // CONFIG_SD_CARD_MMC_INTERFACE

#ifdef CONFIG_SD_CARD_SPI_INTERFACE
#define CARD_SPI_MOSI_GPIO GPIO_NUM_2
#define CARD_SPI_MISO_GPIO GPIO_NUM_1
#define CARD_SPI_SCLK_GPIO GPIO_NUM_3
#define CARD_SPI_CS_GPIO   GPIO_NUM_46
#endif // CONFIG_SD_CARD_SPI_INTERFACE

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_12

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_42
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#ifdef CONFIG_JIUCHUAN_S3_V2
#define AUDIO_CODEC_ES7210_ADDR  0x82  // ES7210 I2C address (0x41 << 1)
#endif


#define BUILTIN_LED_GPIO        GPIO_NUM_10
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define PWR_BUTTON_GPIO         GPIO_NUM_3

#ifdef CONFIG_JIUCHUAN_S3_V2
#define PWR_EN_GPIO             GPIO_NUM_15
#define VBAT_ADC_GPIO           GPIO_NUM_4
#define VBUS_ADC_GPIO           GPIO_NUM_5
#define BATTERY_FULL_PIN        GPIO_NUM_16
#else
#define PWR_EN_GPIO             GPIO_NUM_5
#define PWR_ADC_GPIO            GPIO_NUM_4
#endif

#define PWR_BUTTON_TIME         3000000U

#define WIFI_BUTTON_GPIO        GPIO_NUM_6
#define CMD_BUTTON_GPIO         GPIO_NUM_7


#define DISPLAY_SPI_SCK_PIN     GPIO_NUM_41
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_40
#define DISPLAY_DC_PIN          GPIO_NUM_39
#define DISPLAY_SPI_CS_PIN      GPIO_NUM_9

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320

#ifdef CONFIG_JIUCHUAN_S3_V2
#define DISPLAY_MIRROR_X false
#else
#define DISPLAY_MIRROR_X true
#endif

#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_46
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#if defined(CONFIG_JIUCHUAN_LCD_JD9853)
#define LCD_DRIVER_TYPE 2
#else
#define LCD_DRIVER_TYPE 1
#endif


#endif // _BOARD_CONFIG_H_
